/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hisense_motionkit_MotionMonitorController */

#ifndef _Included_com_hisense_motionkit_MotionMonitorController
#define _Included_com_hisense_motionkit_MotionMonitorController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hisense_motionkit_MotionMonitorController
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hisense_motionkit_MotionMonitorController_startMonitor
  (JNIEnv *, jclass);

/*
 * Class:     com_hisense_motionkit_MotionMonitorController
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hisense_motionkit_MotionMonitorController_stopMonitor
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
