/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhouhao2_debug_Test */

#ifndef _Included_com_zhouhao2_debug_Test
#define _Included_com_zhouhao2_debug_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhouhao2_debug_Test
 * Method:    setConfiguration
 * Signature: (Lcom/zhouhao2/debug/CustomConfiguration;)V
 */
JNIEXPORT void JNICALL Java_com_zhouhao2_debug_Test_setConfiguration
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_zhouhao2_debug_Test
 * Method:    initArray
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zhouhao2_debug_Test_initArray
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
